"""added debi column

Revision ID: 124b75b5a37d
Revises: 337ac9301abe
Create Date: 2025-11-13 10:54:44.863748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124b75b5a37d'
down_revision = '337ac9301abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('debi', sa.String(length=50), nullable=True))
    op.drop_column('sales', 'debit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('debit', sa.BOOLEAN(), nullable=True))
    op.drop_column('sales', 'debi')
    # ### end Alembic commands ###
