"""updating new structure

Revision ID: 4f3238c374ec
Revises: 
Create Date: 2025-11-15 15:57:02.988387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3238c374ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('expenses',
    sa.Column('expenseid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('cost_per_unit', sa.String(length=50), nullable=True),
    sa.Column('productname', sa.String(length=255), nullable=True),
    sa.Column('credit', sa.String(length=50), nullable=True),
    sa.Column('paymentmethod', sa.String(length=50), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('expenseid')
    )
    op.create_table('sales',
    sa.Column('salesid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('price_per_unit', sa.String(length=50), nullable=True),
    sa.Column('productname', sa.String(length=255), nullable=True),
    sa.Column('debi', sa.String(length=50), nullable=True),
    sa.Column('paymentmethod', sa.String(length=50), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('salesid')
    )
    op.create_table('stock',
    sa.Column('stockid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('productname', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('buyingprice', sa.String(length=50), nullable=True),
    sa.Column('debit_credit', sa.String(length=50), nullable=True),
    sa.Column('stockstatus', sa.String(length=50), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('stockid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_table('sales')
    op.drop_table('expenses')
    op.drop_table('users')
    # ### end Alembic commands ###
