"""added some columns in stock table

Revision ID: ca780297ca96
Revises: 124b75b5a37d
Create Date: 2025-11-15 13:35:52.076447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca780297ca96'
down_revision = '124b75b5a37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('buyingprice', sa.String(length=50), nullable=True))
    op.add_column('stock', sa.Column('debit_credit', sa.String(length=50), nullable=True))
    op.add_column('stock', sa.Column('stockstatus', sa.String(length=50), nullable=True))
    op.drop_column('stock', 'expectedprofit')
    op.drop_column('stock', 'sellingprice')
    op.drop_column('stock', 'Stockstatus')
    op.drop_column('stock', 'debit')
    op.drop_column('stock', 'costprice')
    op.drop_column('stock', 'credit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('credit', sa.BOOLEAN(), nullable=True))
    op.add_column('stock', sa.Column('costprice', sa.VARCHAR(length=50), nullable=True))
    op.add_column('stock', sa.Column('debit', sa.BOOLEAN(), nullable=True))
    op.add_column('stock', sa.Column('Stockstatus', sa.VARCHAR(length=50), nullable=True))
    op.add_column('stock', sa.Column('sellingprice', sa.VARCHAR(length=255), nullable=True))
    op.add_column('stock', sa.Column('expectedprofit', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('stock', 'stockstatus')
    op.drop_column('stock', 'debit_credit')
    op.drop_column('stock', 'buyingprice')
    # ### end Alembic commands ###
